---
title: "SnowPit_2021_22"
author: "Wyatt Reis"
date: "5/23/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(lubridate)
library(plotly)
library(ggplot2)
library(readxl)
```

```{r}
## Import All Snow Pit Data

file.list <- list.files(pattern='*.xlsx', recursive = TRUE)  

name.list <- list.files(pattern='*.xlsx', recursive = TRUE) %>%
  gsub('PitSheets/pits_', '',.) %>%
  gsub('.xlsx', '',.)

for (i in seq_along(file.list)){
  
  sheet_nm <- excel_sheets(file.list[i])

    for (j in seq_along(sheet_nm)){
  
       assign(x = paste0("pits_", name.list[i]), value = bind_rows(lapply(setNames(sheet_nm,sheet_nm), function(x) read_excel(file.list[i], sheet =x, skip = 7)),.id = "pit")) 
    }
}

pits_list <-mget(ls(pattern = "pits_.*"))

all_pits <- bind_rows(pits_list, .id = "date") %>%
  mutate(date = str_remove(date, "pits_"), date = as.POSIXct(date, format = "%Y%m%d"), date = as.Date(date)) %>%
  select(-c(10,13))

```

```{r fig.width=12,fig.height=7}
## Temperature profiles
temp_prof<- ggplot(all_pits) +
  geom_path(aes(x = temp_C, y= heightAG, color = date, linetype = pit)) +
  ggtitle("Snow Pit Temp Profiles") 
ggplotly(temp_prof)

```

```{r fig.width=12,fig.height=7}
## Snow Pit Density 

pit_avg <- all_pits %>%
  mutate(density_avg = rowMeans(.[,5:7], na.rm = TRUE), perm_avg = rowMeans(.[,8:9], na.rm = TRUE)) %>%
  group_by(date, pit) %>%
  summarise(SDmax = max(heightAG, na.rm = TRUE), density_avg = mean(density_avg, na.rm = TRUE), perm_avg = mean(perm_avg, na.rm = TRUE)) %>%
  mutate(weight = (SDmax/100)*1.5*(SDmax/100)*1.5*density_avg)

totalweight = sum(pit_avg$weight)

```

